### ISSUE TITLE
create online browsable version?

### ISSUE THREAD

**Issue by mikemoraned** [ddinchev/conway-game-of-life-js#1]
Hi,

It's very easy to create an online browsable version: just create a "gh-pages" branch. I've down so in my fork, so http://mikemoraned.github.io/conway-game-of-life-js/ now exists.

See: https://help.github.com/articles/user-organization-and-project-pages/

Thanks,

Mike

**Comment by ddinchev** [comment]
Sweet, thanks! I did so:
http://ddinchev.github.io/conway-game-of-life-js/
